Fixed function await_proxyfsd_startup to ensure proxyfsd stays up

diff --git a/saio/bin/start_and_mount_pfs b/saio/bin/start_and_mount_pfs
--- a/saio/bin/start_and_mount_pfs
+++ b/saio/bin/start_and_mount_pfs
@@ -16,14 +16,14 @@ function await_proxyfsd_shutdown {
 }
 
 function await_proxyfsd_startup {
-    /usr/bin/systemctl -q is-active proxyfsd
-    if [ $? -ne 0 ]
-    then
-        echo "ProfyFS failed to start. Exiting..."
-        exit 1
-    fi
     while true
     do
+        /usr/bin/systemctl -q is-active proxyfsd
+        if [ $? -ne 0 ]
+        then
+            echo "ProfyFS failed to start. Exiting..."
+            exit 1
+        fi
         curl http://127.0.0.1:15346/ 2>/dev/null >/dev/null
         if [ $? -eq 0 ]
         then
