Added mkproxyfs step to SAIO for ProxyFS VM's start scripts

diff --git a/saio/bin/start_and_mount_pfs b/saio/bin/start_and_mount_pfs
--- a/saio/bin/start_and_mount_pfs
+++ b/saio/bin/start_and_mount_pfs
@@ -21,7 +21,7 @@ function await_proxyfsd_startup {
         /usr/bin/systemctl -q is-active proxyfsd
         if [ $? -ne 0 ]
         then
-            echo "ProfyFS failed to start. Exiting..."
+            echo "ProxyFS failed to start. Exiting..."
             exit 1
         fi
         curl http://127.0.0.1:15346/ 2>/dev/null >/dev/null
@@ -31,6 +31,15 @@ function await_proxyfsd_startup {
         fi
         sleep 1
     done
+}
+
+function format_volume_if_necessary {
+    /vagrant/bin/mkproxyfs -I $1 /vagrant/src/github.com/swiftstack/ProxyFS/saio/proxyfs.conf
+    if [ $? -ne 0 ]
+    then
+        echo "Could not pre-format $1"
+        exit 1
+    fi
 }
 
 if [ $# -gt 0 ]; then
@@ -106,6 +115,7 @@ if [ -f /usr/bin/systemctl ]; then
     sudo /usr/bin/systemctl start memcached
     # sudo /usr/bin/systemctl start swift
     sudo /usr/bin/swift-init main start
+    format_volume_if_necessary CommonVolume
     sudo /usr/bin/systemctl start proxyfsd
     await_proxyfsd_startup
     # sudo /usr/bin/systemctl start winbind
@@ -134,6 +144,7 @@ else
     sudo /usr/sbin/service memcached start
     # sudo /usr/sbin/service swift start
     sudo /usr/bin/swift-init main start
+    format_volume_if_necessary CommonVolume
     sudo /usr/sbin/service proxyfsd start
     await_proxyfsd_startup
     # sudo /usr/sbin/service winbindd start
