Changes in start_and_mount_pfs and unmount_and_stop_pfs
- The default protocol version for SMB is now 3.0.
- If you pass 'keepmounts' as the only argument, the scripts will only
stop (and start) the services, but they will NOT unmount/mount any
shares.

diff --git a/saio/bin/unmount_and_stop_pfs b/saio/bin/unmount_and_stop_pfs
--- a/saio/bin/unmount_and_stop_pfs
+++ b/saio/bin/unmount_and_stop_pfs
@@ -21,14 +21,27 @@ SHARE_NFS=/mnt/nfs_proxyfs_mount/
 MOUNT_POINT_SMB=//127.0.0.1/proxyfs
 SHARE_SMB=/mnt/smb_proxyfs_mount
 
-mountpoint -q $SHARE_NFS
-if [ $? -eq 0 ]; then
-    sudo umount $SHARE_NFS
+if [ $# = 0 ]; then
+    SHOULD_UNMOUNT=1
+else
+    if [ $1 = "keepmounts" ]; then
+        SHOULD_UNMOUNT=0
+    else
+        echo "Invalid argument: $1"
+        exit 1
+    fi
 fi
 
-mountpoint -q $SHARE_SMB
-if [ $? -eq 0 ]; then
-    sudo umount $SHARE_SMB
+if [ $SHOULD_UNMOUNT = 1 ]; then
+    mountpoint -q $SHARE_NFS
+    if [ $? -eq 0 ]; then
+        sudo umount $SHARE_NFS
+    fi
+
+    mountpoint -q $SHARE_SMB
+    if [ $? -eq 0 ]; then
+        sudo umount $SHARE_SMB
+    fi
 fi
 
 if [ -f /usr/bin/systemctl ]; then
