SMB protocol multi-version support on start_and_mount_pfs

diff --git a/cookbooks/proxyfs/templates/default/usr/bin/start_and_mount_pfs.erb b/cookbooks/proxyfs/templates/default/usr/bin/start_and_mount_pfs.erb
--- a/cookbooks/proxyfs/templates/default/usr/bin/start_and_mount_pfs.erb
+++ b/cookbooks/proxyfs/templates/default/usr/bin/start_and_mount_pfs.erb
@@ -11,6 +11,7 @@ function await_proxyfsd_shutdown {
         then
             break
         fi
+        echo "Waiting for ProxyFS to be stopped..."
         sleep 1
     done
 }
@@ -29,6 +30,20 @@ function await_proxyfsd_startup {
         then
             break
         fi
+        echo "Waiting for ProxyFS to be started..."
+        sleep 1
+    done
+}
+
+function await_swift_startup {
+    while true
+    do
+        curl http://127.0.0.1:8090/info 2>/dev/null >/dev/null
+        if [ $? -eq 0 ]
+        then
+            break
+        fi
+        echo "Waiting for Swift to be started..."
         sleep 1
     done
 }
@@ -36,12 +51,34 @@ function await_proxyfsd_startup {
 if [ $# -gt 0 ]; then
     MOUNT_TYPE="$1"
     MOUNT_TYPE=${MOUNT_TYPE,,}
-    if [ "$MOUNT_TYPE" != "all" ] && [ "$MOUNT_TYPE" != "smb" ] && [ "$MOUNT_TYPE" != "nfs" ]; then
-        echo "Invalid argument $1"
+    if [ "$MOUNT_TYPE" != "all" ] && [ "$MOUNT_TYPE" != "smb" ] && [ "$MOUNT_TYPE" != "smb1" ] && [ "$MOUNT_TYPE" != "smb2" ] && [ "$MOUNT_TYPE" != "smb3" ] && [ "$MOUNT_TYPE" != "nfs" ]; then
+        echo "Invalid argument '$1'."
+        echo
+        echo "Usage: $0 [mount type]"
+        echo "Mount type options:"
+        echo "    all: NFS v3 and SMB v1.0 (default option)"
+        echo "    nfs: NFS v3"
+        echo "    smb: SMB v1.0"
+        echo "    smb1: SMB v1.0"
+        echo "    smb2: SMB v2.1"
+        echo "    smb3: SMB v3.0"
         exit 1
     fi
 else
     MOUNT_TYPE=all
+fi
+
+if [ "$MOUNT_TYPE" == "all" ]; then
+    NFS_VERS=3
+    SMB_VERS=1.0
+elif [ "$MOUNT_TYPE" == "nfs" ]; then
+    NFS_VERS=3
+elif [ "$MOUNT_TYPE" == "smb" ] || [ "$MOUNT_TYPE" == "smb1" ]; then
+    SMB_VERS=1.0
+elif [ "$MOUNT_TYPE" == "smb2" ]; then
+    SMB_VERS=2.1
+elif [ "$MOUNT_TYPE" == "smb3" ]; then
+    SMB_VERS=3.0
 fi
 
 MOUNT_POINT_NFS=127.0.0.1:/CommonMountPoint
@@ -49,6 +86,9 @@ SHARE_NFS=/mnt/nfs_proxyfs_mount/
 
 MOUNT_POINT_SMB=//127.0.0.1/proxyfs
 SHARE_SMB=/mnt/smb_proxyfs_mount
+
+UID_SMB=`id -u`
+GID_SMB=`id -g`
 
 sudo mount -a
 
@@ -81,6 +121,7 @@ if [ -f /usr/bin/systemctl ]; then
     sudo /usr/bin/systemctl start memcached
     # sudo /usr/bin/systemctl start swift
     sudo /usr/bin/swift-init main start
+    await_swift_startup
     sudo /usr/bin/systemctl start proxyfsd
     await_proxyfsd_startup
     # sudo /usr/bin/systemctl start winbind
@@ -109,6 +150,7 @@ else
     sudo /usr/sbin/service memcached start
     # sudo /usr/sbin/service swift start
     sudo /usr/bin/swift-init main start
+    await_swift_startup
     sudo /usr/sbin/service proxyfsd start
     await_proxyfsd_startup
     # sudo /usr/sbin/service winbindd start
@@ -127,7 +169,7 @@ if [ $MOUNT_TYPE = "all" ] || [ $MOUNT_TYPE = "nfs" ]; then
     if [ $? -ne 0 ]; then
         for i in `seq 5`; do
             sleep 5
-            sudo $MOUNT -t nfs -o vers=3 $MOUNT_POINT_NFS $SHARE_NFS && break
+            sudo $MOUNT -t nfs -o vers=$NFS_VERS $MOUNT_POINT_NFS $SHARE_NFS && break
             echo "Mount of $SHARE_NFS failed.  Retrying..."
         done
     fi
@@ -141,12 +183,12 @@ if [ $MOUNT_TYPE = "all" ] || [ $MOUNT_TYPE = "nfs" ]; then
     fi
 fi
 
-if [ $MOUNT_TYPE = "all" ] || [ $MOUNT_TYPE = "smb" ]; then
+if [ $MOUNT_TYPE = "all" ] || [ $MOUNT_TYPE = "smb" ] || [ $MOUNT_TYPE = "smb1" ] || [ $MOUNT_TYPE = "smb2" ] || [ $MOUNT_TYPE = "smb3" ]; then
     mountpoint -q $SHARE_SMB
     if [ $? -ne 0 ]; then
         for i in `seq 5`; do
             sleep 5
-            sudo $MOUNT -t cifs -o user=<%= @swift_user %>,password=<%= @swift_user %>,domain=LOCALHOST,vers=1.0 $MOUNT_POINT_SMB $SHARE_SMB && break
+            sudo $MOUNT -t cifs -o user=<%= @swift_user %>,password=<%= @swift_user %>,domain=LOCALHOST,uid=$UID_SMB,gid=$GID_SMB,vers=$SMB_VERS $MOUNT_POINT_SMB $SHARE_SMB && break
             echo "Mount of $SHARE_SMB failed.  Retrying..."
         done
     fi
